language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang
  
cache: apt

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update

install:
  - sudo apt-get install -y cmake

script:
  - cmake .
  - make tiled-reader
  - make tiledreader_test
  - cd ./test && ./ugdk_test

